server:
  port: 9999

spring:
  datasource:
    username: root
    password: 1234
    url: jdbc:mysql:///study

#  redis:
#    port: 6379
#    host: 192.168.32.132
#    password: 12345

logging:
  level:
    com.jxau: debug

mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0
  type-aliases-package: com.jxau.*.entity
